#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define TAPPING_TERM 160
// #define COMBO_TERM 500
// #define PERMISSIVE_HOLD
#define CAPSWORD_USE_SHIFT
#define VIM_FOR_ALL
#define _VIM_TEXT_OBJECTS
#define VIM_I_TEXT_OBJECTS
#define VIM_A_TEXT_OBJECTS
#define VIM_G_MOTIONS
#define VIM_COLON_CMDS
#define VIM_PASTE_BEFORE
#define VIM_REPLACE
#define VIM_DOT_REPEAT
#define VIM_W_BEGINNING_OF_WORD
#define VIM_NUMBERED_JUMPS
